SportsStore.WebUI/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get
            {
                return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
            }
        }
    }
}

SportsStore.WebUI/Models/ProductListViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

SportsStore.WebUI/Controllers/AdminController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository repository;

        public AdminController(IProductRepository repo)
        {
            repository = repo;
        }

        public ActionResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int productID)
        {
            Product product = repository.Products.First(s => s.ProductID == productID);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduct(product);
                TempData["message"] = string.Format("Zapisano {0} ", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        public ActionResult Delete(int productID)
        {
            Product deletedProduct = repository.DeleteProduct(productID);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("Usunięto {0}", deletedProduct.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

SportsStore.WebUI/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }


        public RedirectToRouteResult AddToCart(Cart cart, int productID, string returnUrl)
        {
            var Product = repository.Products.FirstOrDefault(s => s.ProductID == productID);
            if (Product != null)
                cart.AddItem(Product, 1);

            return RedirectToAction("Index", new { returnUrl });

        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productID, string returnUrl)
        {
            var Product = repository.Products.FirstOrDefault(s => s.ProductID == productID);
            if (Product != null)
                cart.RemoveLine(Product);

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingdetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Koszyk jest pusty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingdetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingdetails);
            }
        }
    }
}

SportsStore.WebUI/Controllers/NavController.cs
using SportsStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        
        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products.Select(s => s.Category)
                                                .Distinct()
                                                .OrderBy(s => s);

            return PartialView("FlexMenu", categories);
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult List(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = repository.Products.Where(s => category == null || category == s.Category)
                                              .OrderBy(s => s.ProductID)
                                              .Skip((page - 1) * PageSize)
                                              .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                                 repository.Products.Count() :
                                 repository.Products.Where(s => s.Category == category).Count()
                },

                CurrentCategory = category
            };

            return View(model);

        }
    }
}

SportsStore.WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{
    ViewBag.Title = "Administracja: edycja " + Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Edycja @Model.Name</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin"))
    {
        <div class="panel-body">
            @Html.HiddenFor(s => s.ProductID)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "ProductID")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }
        </div>
        <div class="panel-footer">
            <input type="submit" value="Zapisz" class="btn btn-primary" />
            @Html.ActionLink("Anuluj i wróć do listy", "Index", null, new { @class = "btn btn-default" })
        </div>

    }
</div>

SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
    ViewBag.Title = "Administracja: Wszystkie produky";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Wszystkie produkty</h3>
    </div>
</div>
<div class="panel-body">
    <table class="table table-striped table-condensed table-bordered">
        <tr>
            <th>ID</th>
            <th>Nazwa</th>
            <th class="NumericCol">Cena</th>
            <th>Akcje</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ProductID</td>
                <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
                <td class="NumericCol">@item.Price.ToString("c")</td>
                <td>
                    @using (Html.BeginForm("Delete", "Admin"))
                    {
                        @Html.Hidden("ProductID", item.ProductID)
                        <input type="submit" value="Usuń" class="btn btn-sm btn-danger"/>
                    }
                </td>
            </tr>
        }
    </table>
</div>
<div class="panel-footer">
    @Html.ActionLink("Dodaj nowy produkt", "Create", null, new { @class = "btn btn-default" })
</div>

SportsStore.WebUI/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Sklep sportowy: Wysyłka";
}

<h2>Wysyłka</h2>
<p>Proszę podać dwoje dane:</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <h3>Wysyłka dla</h3>
    <div class="form-group">
        <label>Nazwisko:</label>
        @Html.TextBoxFor(s => s.Name, new { @class = "form-control" })
    </div>

    <h3>Adres</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control"})
            </div>
        }
    }

    <h3>Opcje</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(s => s.GiftWrap)
            Zapakowanie jako prezent
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Zakończ zamówienie"/>
    </div>
}

SportsStore.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Zamówienie w drodze";
}

<h2>Dziękujemy!</h2>
Dziękujemy za złożenie zamowienia. Nasz kurier już do Ciebie jedzie.

SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Sklep sportowy: Twój koszyk";
}

<style>
    #cartTable td {vertical-align: middle;}
</style>

<h2>Twój koszyk</h2>

<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Ilość</th>
            <th>Produkt</th>
            <th class="text-right">Cena</th>
            <th class="text-right">Wartość</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-right">@((line.Quantity * line.Product.Price).ToString("c"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductID)
                        @Html.HiddenFor(s => s.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Usuń"/>
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Razem: </td>
            <td class="text-right">@Model.Cart.ComputeTotalValue().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Kontynuuj zakupy</a>
    @Html.ActionLink("Złóż zamówienie", "Checkout", null, new { @class = "btn btn-primary"})
</div>

SportsStore.WebUI/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart

<div class="navbar-right hidden-xs">
    @Html.ActionLink("Zamów", "Index", "Cart", 
    new { returnUrl = Request.Url.PathAndQuery}, 
    new {@class = "btn btn-default navbar-btn"})
</div>

<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index", "Cart", new { returnUrl = Request.Url.PathAndQuery})
       class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>

<div class="navbar-text navbar-right">
    <b class="hidden-xs">Twój koszyk:</b>
    @Model.Lines.Sum(s => s.Quantity) sztuk,
    @Model.ComputeTotalValue().ToString("c")
</div>

SportsStore.WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{
    bool horizontal = ((bool)(ViewContext.RouteData.Values["horizontalLayout"] ?? false));
    string wrapperClasses = horizontal ? "btn-group btn-group-sm btn-group-justified" : null;
}

<div class="@wrapperClasses">
    @Html.ActionLink("Home", "List", "Product", null, new { @class = horizontal ?
    "btn btn-default btn-sm"
    : "btn btn-block btn-default btn-lg" })



@foreach (var link in Model)
{
    @Html.RouteLink(link, new { controller = "Product", action = "List", category = link, page = 1, },
    new { @class = horizontal ? "btn btn-default btn-sm" : "btn btn-block btn-default btn-lg" 
    + (link == ViewBag.SelectedCategory ? " btn-primary" : "") })
}

</div>

SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product", null, new { @class = "btn btn-block btn-default btn-lg" })
@foreach (var link in Model)
{
    @Html.RouteLink(link, new { controller = "Product", action = "List", category = link, page = 1, },
    new { @class = "btn btn-block btn-default btn-lg" + (link == ViewBag.SelectedCategory ? " btn-primary" : "") })
}

SportsStore.WebUI/Views/Nav/MenuHorizontal.cshtml
@model IEnumerable<string>


<div class="btn-group btn-group-sm btn-group-justified">
    @Html.ActionLink("Home", "List", "Product", new { @class = "btn btn-default btn-sm" })
    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new { controller = "Product", action = "List", category = link, page = 1, },
    new { @class = "btn btn-default btn-sm" + (link == ViewBag.SelectedCategory ? " btn-primary" : "") })
    }
</div>

SportsStore.WebUI/Views/Product/List.cshtml
@using SportsStore.Domain.Entities
@model SportsStore.WebUI.Models.ProductListViewModel

@{
    ViewBag.Title = "Produkty";
}

@foreach(var p in Model.Products)
{
    @Html.Partial("ProductSummary", p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">

    <h4 class="visible-xs">
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h4>

    <h3 class="hidden-xs">
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>

    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(s => s.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="visible-xs btn btn-success btn-xs" value="Dodaj do koszyka" />
            <input type="submit" class="hidden-xs btn btn-success" value="Dodaj do koszyka" />
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>   

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    @*<script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>*@
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
     <!--Autor: Mariusz Madalinski -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet"/>
    <link href="~/Content/ErrorSyles.css" rel="stylesheet"/>
    <title>@ViewBag.Title </title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px; margin-left: 15px;
        }
    </style>
</head>
<body>

    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">Sklep sportowy</span>
            <div class="visible-xs">Sklep</div>
            <div class="visible-xs">Sportowy</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalLayout = true })
    </div>
    <div class="container-fluid">
        <div class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
       </div>
   </div>
</body>
</html>